### ISSUE TITLE
Split into separate library and executable packages

### ISSUE THREAD

**Issue by boris-kolpackov** [Klaim/lua-build2#2]
At some point we may want to split this into two (or three) packages: library (probably `liblua`) and the executable(s) (`lua` and `luac`), similar to how Debain does it (see, for example, `lua5.1` and `liblua5.1[-dev]` packages currently in stable).

The main motivation for this is to be able to build the library and the tools for different targets when cross-compiling. The fact that most users will want only the library and thus will avoid building the executables unnecessarily is also a plus.

**Comment by Klaim** [comment]
Thanks, I didn't know that it was distributed that way as I mainly followed the makefile from the source package.

**Comment by boris-kolpackov** [comment]
FYI: https://github.com/build2/build2/issues/331#issuecomment-1784980261

**Comment by lyrahgames** [comment]
This issue is closed for now. Feel free to re-open.
