### ISSUE TITLE
`c.std=gnu99` cannot be used with MSVC

### ISSUE THREAD

**Issue by boris-kolpackov** [Klaim/lua-build2#4]
In the upcoming `build2` release (`0.17.0`) we have tightened the `c.std` value check for MSVC. For details, see: https://github.com/build2/build2/issues/383

That change uncovered that this package uses `c.std=gnu99` which, naturally, cannot be satisfied by MSVC. So it would be helpful to fix this with a revision before the `0.17.0` release (in a few weeks).

As to how to fix this, I think it would be good to first understand whether the `gnu` part is actually necessary by trying to CI the package with `c.std=99`. If it runs out it's not necessary, then that's the fix. Of course, it's possible that the source code detects whether the GNU extensions are available and does something suboptimal if not, so it makes sense to also check the source code and upstream documentation.

If it turns out that `gnu99` is necessary, then the correct way to do it is:

```
using c.guess

c.std = ($c.class == 'gcc' ? gnu99 : 99)

using c
```

**Comment by Klaim** [comment]
Thanks @wroyca , I'll try to push the revision packages ASAP.

**Comment by Klaim** [comment]
I `bdep publish`-ed [`v5.4.3+4`](https://queue.cppget.org/lua/5.4.3+4) and [last v5.3 version](https://queue.cppget.org/lua/5.3.5+3), I lack time for `v5.4.0`, `v5.4.1` and `v5.4.2` but hopefully most users will just take latest `v5.4` or `v5.3` which are now fixed. If you prefer I make the revision for the other versions I'll try in the week.

**Comment by boris-kolpackov** [comment]
Thanks, I think the last two minor versions is more than enough. We can always publish revisions for others if/when someone complains (and gives a convincing explanation why upgrading is not an option).
